services:
  nginx:
    image: nginx:alpine
    container_name: tardis-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: tardis-backend
    privileged: true # For GPIO access on rPi
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/certs:/app/certs
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - AUDIODRIVER=alsa
      - AUDIODEV=plughw:2,0

  frontend:
    build: ./frontend
    container_name: tardis-frontend
    depends_on:
      - backend
    restart: unless-stopped
