services:
  backend:
    image: tardis-lights-backend:latest
    container_name: tardis-backend
    ports:
      - "8000:8000"
    privileged: true
    restart: unless-stopped

  frontend:
    image: tardis-lights-frontend:latest
    container_name: tardis-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped